# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiko < Formula
  desc "A simple TUI gRPC client"
  homepage "https://github.com/felangga/chiko"
  version "0.0.4"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/felangga/chiko/releases/download/v0.0.4/chiko_0.0.4_darwin_amd64.tar.gz"
      sha256 "aec071a0e7095bc785b906f11b5da83ba4dc030ff73386f773f1b2e20a49161b"

      def install
        bin.install "chiko"
      end
    end
    on_arm do
      url "https://github.com/felangga/chiko/releases/download/v0.0.4/chiko_0.0.4_darwin_arm64.tar.gz"
      sha256 "bd4062d737993d920d047e55aae2c2f960c7a04f96265986d94e388bdcee63fa"

      def install
        bin.install "chiko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.4/chiko_0.0.4_linux_amd64.tar.gz"
        sha256 "b7b8550c107cc8c14446f99d6670ce5082cfaa777c79f950b4f1f837f65d5c49"

        def install
          bin.install "chiko"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.4/chiko_0.0.4_linux_arm64.tar.gz"
        sha256 "f6a09a16ff499eeec99c7513f78a7c4ba574317b3d375acf1b81ef873cc64fc1"

        def install
          bin.install "chiko"
        end
      end
    end
  end
end
