# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiko < Formula
  desc "A simple TUI gRPC client"
  homepage "https://github.com/felangga/chiko"
  version "0.0.1"
  license "MIT"

  depends_on "go"

  on_macos do
    on_intel do
      url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_darwin_amd64.tar.gz"
      sha256 "cba0dd6ef0c46bccd398dd3b0bcdb71a4f44cedf059a6a7d180b97f2e297e3b6"

      def install
        bin.install "chiko"
      end
    end
    on_arm do
      url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_darwin_arm64.tar.gz"
      sha256 "3ba77dc431fa69b7db1d395f10e6c0a72455d67d2b51f1c8fa49219b0bf956a5"

      def install
        bin.install "chiko"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_linux_amd64.tar.gz"
        sha256 "31e6bb3d1ce1a2de5a5ac416552b561c2a90facf474af36e27b7e145a53789d8"

        def install
          bin.install "chiko"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.1/chiko_0.0.1_linux_arm64.tar.gz"
        sha256 "03f6d64507026fe2f7016d1b8de09041c402efa2ea44e950c9f8814dcd21423e"

        def install
          bin.install "chiko"
        end
      end
    end
  end
end
