# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chiko < Formula
  desc "A simple TUI gRPC client"
  homepage "https://github.com/felangga/chiko"
  version "0.0.5"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felangga/chiko/releases/download/v0.0.5/chiko_0.0.5_darwin_amd64.tar.gz"
      sha256 "c643ab9bb35c2a7125790d285f53bfff32904dc22a87da98d50e104f2d950c80"

      def install
        bin.install "chiko"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felangga/chiko/releases/download/v0.0.5/chiko_0.0.5_darwin_arm64.tar.gz"
      sha256 "95eba7ed2aa1d8628491d925eef15e52d54da3b76f36650fe6d8400df01cc440"

      def install
        bin.install "chiko"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.5/chiko_0.0.5_linux_amd64.tar.gz"
        sha256 "8770b490ee38966308724fb2cd88ab4a0e3d8762374c5dbe2df3cdad6506a9dc"

        def install
          bin.install "chiko"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/felangga/chiko/releases/download/v0.0.5/chiko_0.0.5_linux_arm64.tar.gz"
        sha256 "9cbbb697d9c26ea1e5c5a848a3d10c1c88b11eb2518fa421e5fcf71c04a7b47d"

        def install
          bin.install "chiko"
        end
      end
    end
  end
end
